# Generated by Django 4.2.7 on 2023-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal_grievance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquery',
            name='branch',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'ME'), (3, 'CIVIL'), (4, 'EC'), (5, 'CSBS'), (6, 'IT'), (7, 'RPC'), (8, 'CE')], default=0),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='sem',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII')], default=1),
        ),
    ]
